### PR TITLE
fix old string msats fields and parse as uint64 instead

### PR DESCRIPTION
**Pull request by chrisguida**
Fixes the `listfunds` call. Draft until I can fix the rest of the broken msat fields.

### CODE REVIEW

**Comment by nepet** [comment]
Hey @chrisguida
Thanks for starting to fix the broken fields. We need a fixed version of all the msat fields for peerswap to support cln `v23.05` soon. Are you okay if I take over and fix the remaining broken fields?

**Comment by chrisguida** [comment]
Yes, that's fine. I assume you mean you'll be adding to this PR?

**Comment by chrisguida** [comment]
Let me know how I can help get this across the finish line :)

**Comment by nepet** [comment]
Hey @chrisguida, thanks for offering your help here! I was busy yesterday but I will try to finish this up tonight so that we can start to test the changes?

I added the `Amount` type to help support `v23.02` as well as the upcoming `v23.05`. Any thoughts about that?

**Comment by chrisguida** [comment]
I'm not seeing the `Amount` change you're referring to, can you elaborate?

**Comment by nepet** [comment]
Oh silly me did not push it yet, let mu push an WIP state

**Comment by nepet** [comment]
Ok we can try to test the implementation against the rc and the old version now. I will report back once I got first results.

**Comment by chrisguida** [comment]
Cool, what are you using to test? Just running glightning vs two different versions of CLN? Or is there a test suite here in glightning I'm unaware of?

**Comment by nepet** [comment]
I am testing it running it from the peerswap plugin against two versions of cln (v23.02 vs. v23.05)

So I might have forgotten some of the fields ^^

**Comment by nepet** [comment]
Seems that it is backwards compatible as far as I can tell from peerswap, using the `Amount` fields.

**Comment by nepet** [comment]
We had some tests over at peerswap, seems to be stable for what we can tell.

**Comment by chrisguida** [comment]
🎉

**Pull request merged**
